using AutoMapper;
using CodePulse.API.Data;
using CodePulse.API.Mappings;
using CodePulse.API.Models.Domain;
using CodePulse.API.Models.DTO;
using Microsoft.AspNetCore.Mvc;
using CodePulse.API.Repositories;

namespace CodePulse.API.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class CategoriesController : ControllerBase
    {
        private readonly IMapper _mapper;
        private readonly ICategoryRepository categoryRepository;

        public CategoriesController(IMapper mapper, ICategoryRepository categoryRepository)
        {
            _mapper = mapper;
            this.categoryRepository = categoryRepository;
        }

        //create category
        [HttpPost]
        public async Task<IActionResult> CreateCategory([FromBody] CreateCategoryRequestDto requestDto)
        {
            //map the request to the domain model
            //here guid will be generated by the database when we save the category, so we don't need to set it here
            var category = _mapper.Map<Category>(requestDto);

            //save the category to the database
            await categoryRepository.CreateCategoryAsync(category);

            //map the domain model to the response DTO
            //here guid
            var categoryResponseDto = _mapper.Map<CategoryDto>(category);
            //return CreatedAtAction(nameof(GetCategoryById), new { id = category.Id }, categoryResponseDto);
            return Ok(categoryResponseDto);
        }

        //get all categories
        [HttpGet]
        public async Task<IActionResult> GetAllCategories()
        {
            //what happein here explain the code in detail
            //we call the GetAllCategoriesAsync() method of the category repository to get all categories from the database.
            //This method returns an IEnumerable<Category>, which is a collection of Category objects.
            var categories = await categoryRepository.GetAllCategoriesAsync();
            var categoryDtos = _mapper.Map<List<CategoryDto>>(categories);
            return Ok(categoryDtos);
        }

        //get category by id
        [HttpGet("{id:guid}")]
        public async Task<IActionResult> GetCategoryById([FromRoute] Guid id)
        {
            var category = await categoryRepository.GetCategoryByIdAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            var categoryDto = _mapper.Map<CategoryDto>(category);
            return Ok(categoryDto);
        }

        //put update category
        [HttpPut("{id:guid}")]
        public async Task<IActionResult> UpdateCategory([FromRoute] Guid id, [FromBody] UpdateCategoryRequestDto requestDto)
        {
            var category = await categoryRepository.GetCategoryByIdAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            //map the request to the domain model
            _mapper.Map(requestDto, category);
            //update the category in the database
            await categoryRepository.UpdateCategoryAsync(category);
            return NoContent();
        }
    }
}
